language: generic

## We need super-user permissions to use docker
sudo: required

## Specifying that we need a copy of docker on our running container
services: 
  - docker

## Commands we'll need before running the tests
before_install:
  - docker build -t robperch/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=True robperch/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-511614047400"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
