version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules ## avoid mapping this folder with the docker files
      - .:/app
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules ## avoid mapping this folder with the docker files
      - .:/app
    command: ["npm", "run", "test"] ## overriding the default command specified in the original dockerfile
